# Generated by Django 4.2.30 on 2026-04-26 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=100)),
                ("joining_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pub_type",
                    models.CharField(
                        choices=[
                            ("Journal", "Journal"),
                            ("Conference", "Conference"),
                            ("Book Chapter", "Book Chapter"),
                            ("Book", "Book"),
                        ],
                        max_length=50,
                        verbose_name="Publication Type",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "venue_name",
                    models.CharField(
                        max_length=500, verbose_name="Journal/Conference/Book Name"
                    ),
                ),
                (
                    "issn_isbn",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ISSN / ISBN",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="publications.faculty",
                    ),
                ),
            ],
        ),
    ]
